steps:
  - name: 'maven:3.6.3-jdk-8'
    entrypoint: 'mvn'
    args: ['clean', 'install']
 - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls -lh target']    
options:
  logging: CLOUD_LOGGING_ONLY

