apiVersion: batch/v1
kind: Job
metadata:
  name: maven-job
spec:
  template:
    spec:
      containers:
      - name: maven
        image: gcr.io/maximal-relic-457716-k6/maven-java8   # Imagen de GCR
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      restartPolicy: Never
